<script setup lang="ts">
import {
    House,
    LayoutGrid,
    Users,
    Camera,
    MessageSquare,
    MessagesSquare,
    Wallet,
    LogOut,
    Calendar,
    Clock,
    Bell,
    Play,
    Pause,
    Volume2,
    VolumeX,
    Lock,
    Pill,
    Utensils,
    Activity,
    CalendarClock,
    ArrowDownCircle,
    ArrowUpCircle,
    Send,
    Settings,
    ZoomIn,
    ZoomOut,
    Mic,
    Maximize,
    ShieldCheck,
    ChevronDown,
    Aperture,
    ChevronLeft,
    SkipBack,
    SkipForward,
    CreditCard,
    Phone,
    Cake,
    Stethoscope,
    AlertTriangle,
    Droplet,
    UserCheck,
    MapPin,
    X,
    History,
    Pencil,
    Crown,
    ChevronRight,
    Video,
    ImagePlus,
    UserPlus,
    HeartPulse,
    ClipboardList,
    DoorOpen,
    Star,
    Sun,
    Moon,
    HelpCircle,
    FileText,
    Download,
    Eye,
    Banknote,
    Undo2,
    Building2,
    CheckCircle,
    Loader,
    Info,
    User,
} from "lucide-vue-next";

const icons: Record<string, unknown> = {
    home: House,
    grid: LayoutGrid,
    users: Users,
    camera: Camera,
    message: MessageSquare,
    "messages-square": MessagesSquare,
    wallet: Wallet,
    "log-out": LogOut,
    calendar: Calendar,
    clock: Clock,
    bell: Bell,
    play: Play,
    pause: Pause,
    "volume-2": Volume2,
    "volume-x": VolumeX,
    lock: Lock,
    pill: Pill,
    utensils: Utensils,
    activity: Activity,
    "calendar-clock": CalendarClock,
    "arrow-down-circle": ArrowDownCircle,
    "arrow-up-circle": ArrowUpCircle,
    send: Send,
    settings: Settings,
    "zoom-in": ZoomIn,
    "zoom-out": ZoomOut,
    mic: Mic,
    maximize: Maximize,
    "shield-check": ShieldCheck,
    "chevron-down": ChevronDown,
    aperture: Aperture,
    "chevron-left": ChevronLeft,
    "skip-back": SkipBack,
    "skip-forward": SkipForward,
    "credit-card": CreditCard,
    phone: Phone,
    cake: Cake,
    stethoscope: Stethoscope,
    "alert-triangle": AlertTriangle,
    droplet: Droplet,
    "user-check": UserCheck,
    "map-pin": MapPin,
    x: X,
    history: History,
    pencil: Pencil,
    crown: Crown,
    "chevron-right": ChevronRight,
    video: Video,
    "image-plus": ImagePlus,
    "user-plus": UserPlus,
    "heart-pulse": HeartPulse,
    "clipboard-list": ClipboardList,
    "door-open": DoorOpen,
    star: Star,
    sun: Sun,
    moon: Moon,
    "help-circle": HelpCircle,
    "file-text": FileText,
    download: Download,
    eye: Eye,
    banknote: Banknote,
    "undo-2": Undo2,
    "building-2": Building2,
    "check-circle": CheckCircle,
    loader: Loader,
    info: Info,
    user: User,
};

defineProps<{ name: string }>();
</script>

<template>
    <component :is="icons[name]" :stroke-width="2" />
</template>
